# Delete any platforms you aren't using!

# If you end up getting approved for GitHub Sponsors later:
# github: your_github_username


ko_fi: your_kofi_username
buy_me_a_coffee: your_bmac_username

# You can add up to 4 custom URLs here (like PayPal, a personal website, etc.)
#custom: ['https://paypal.me/yourname', 'https://yourwebsite.com/donate']
